name: Build and Deploy Book Rental Store

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1 - Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2 - Log in to GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Step 3 - Build and push image to ghcr.io
      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/michaelabbeyy134/bookrentalstore:latest

      # Step 4 - SSH into Oracle Linux and deploy
      - name: Deploy to Oracle Linux Server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            # Login to GitHub Container Registry
            echo ${{ secrets.GITHUB_TOKEN }} | \
            sudo podman login ghcr.io \
              --username michaelabbeyy134 \
              --password-stdin

            # Pull latest image
            sudo podman pull ghcr.io/michaelabbeyy134/bookrentalstore:latest

            # Stop and remove old container
            sudo podman rm -f bookrental || true

            # Create db.sqlite3 if it does not exist
            touch /opt/sslmonitor/bookrental-git/db.sqlite3
            mkdir -p /opt/sslmonitor/bookrental-git/media

            # Run new container
            sudo podman run -d \
              --name bookrental \
              --security-opt label=disable \
              -p 8000:8000 \
              -v /opt/sslmonitor/bookrental-git/media:/app/media \
              -v /opt/sslmonitor/bookrental-git/db.sqlite3:/app/db.sqlite3 \
              -e DJANGO_SECRET_KEY='${{ secrets.DJANGO_SECRET_KEY }}' \
              -e DEBUG=1 \
              -e ALLOWED_HOSTS='*' \
              ghcr.io/michaelabbeyy134/bookrentalstore:latest

            # Run migrations
            sudo podman exec bookrental python manage.py migrate