# Generated by Django 5.1.1 on 2024-09-08 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookrentalstore', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rental',
            old_name='rented_at',
            new_name='rented_on',
        ),
    ]
