# Generated by Django 5.1.1 on 2024-09-10 19:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookrentalstore', '0003_rental_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 24, 19, 25, 4, 440775, tzinfo=datetime.timezone.utc)),
        ),
    ]
