# Generated by Django 5.1.1 on 2024-09-10 20:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookrentalstore', '0004_rental_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 24, 20, 12, 5, 795355, tzinfo=datetime.timezone.utc)),
        ),
    ]
