# Generated by Django 5.1.1 on 2024-09-15 21:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookrentalstore', '0005_alter_rental_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 29, 21, 10, 45, 280226, tzinfo=datetime.timezone.utc)),
        ),
    ]
