# Generated by Django 5.1.1 on 2024-09-19 10:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookrentalstore', '0006_book_pdf_alter_rental_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 3, 10, 49, 11, 57834, tzinfo=datetime.timezone.utc)),
        ),
    ]
