# Generated by Django 5.1.1 on 2026-05-22 14:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookrentalstore', '0007_alter_rental_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2026, 6, 5, 14, 0, 7, 996174, tzinfo=datetime.timezone.utc)),
        ),
    ]
