name: Deploy Django App (Podman)

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: SSH Deploy to Oracle Linux Server
        uses: appleboy/ssh-action@v1.0.3

        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}

          script: |
            set -e

            echo "📦 Moving to project directory..."
            cd /opt/sslmonitor/bookrental

            echo "⬇️ Pulling latest code from GitHub..."
            git pull origin master

            echo "🐳 Rebuilding Podman image..."
            podman build -t bookrental:v1 .

            echo "🛑 Stopping old container..."
            podman stop bookrental || true
            podman rm bookrental || true

            echo "🚀 Starting new container..."
            podman run -d \
              --name bookrental \
              -p 8000:8000 \
              -v /opt/sslmonitor/bookrental/media:/app/media:Z \
              -v /opt/sslmonitor/bookrental/db.sqlite3:/app/db.sqlite3:Z \
              -e DJANGO_SECRET_KEY="${{ secrets.DJANGO_SECRET_KEY }}" \
              -e DEBUG=0 \
              -e ALLOWED_HOSTS="10.20.45.11 localhost 127.0.0.1" \
              bookrental:v1

            echo "🔄 Running migrations..."
            podman exec bookrental python manage.py migrate || true

            echo "✅ Deployment complete"
